site_name: frogbox

repo_url: https://github.com/SimonLarsen/frogbox

nav:
- Getting started: index.md
- Reference:
  - Config:
    - Config schema: reference/config/schema.md
    - SupervisedConfig example: reference/config/supervised_example.md
  - Pipelines: reference/pipelines.md
  - Events: reference/events.md
- Guides:
  - Metrics: guides/metrics.md
  - Callbacks:
    - Custom callbacks: guides/callbacks/custom_callbacks.md
    - Logging images: guides/callbacks/logging_images.md
  - Loading a trained model: guides/loading_models.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  palette:
    scheme: slate
    primary: green
    accent: cyan

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: numpy
          modernize_annotations: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_signature_annotations: false
          separate_signature: true
          signature_crossrefs: true
          merge_init_into_class: true
          parameter_headings: true
          show_root_heading: true
          docstring_options:
            ignore_init_summary: true
          show_source: false
          docstring_section_style: list

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true